### ISSUE TITLE
interface of command 'ad' incompatible with inrimage

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#10]
heimdali ad output works as:
`$ ad -o filename3 filename1 filename2`
but should be:
`$ ad filename1 filename2 filename3`

heimdali ad cannot read on stdin. Valid test should be:
`$ cat imtest_z5_y4_x3_c2.h5 | so - imtest_z5_y4_x3_c2.h5 | par`
or
`$ cat imtest_z5_y4_x3_c2.h5 | so imtest_z5_y4_x3_c2.h5 - | par`
or
`$ cat imtest_z5_y4_x3_c2.h5 | so - imtest_z5_y4_x3_c2.h5 | par`

'-' indicates standard input or standard output if the call is ambiguous

**Comment by bereziat** [comment]
same remark holds for 'so'

**Comment by dfroger** [comment]
Fixed in f90c6ab
