### ISSUE TITLE
par and ical do not read from stdin

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#11]
For instance:
`ad imtest_z5_y4_x3_c2.inr imtest_z5_y4_x3_c2.inr | par`
fails

`ad imtest_z5_y4_x3_c2.inr imtest_z5_y4_x3_c2.inr | ical -`
works but not:
`ad imtest_z5_y4_x3_c2.inr imtest_z5_y4_x3_c2.inr | ical`

**Comment by dfroger** [comment]
Fixed in 65b2eeb
