### ISSUE TITLE
ical cannot read inrimage image

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#15]
ical can not read stdin without specify '-' as filename.

`$ h5toinr imtest_z5_y4_x3_c2.h5 imtest_z5_y4_x3_c2.inr`
`$ ical imtest_z5_y4_x3_c2.inr
terminate called after throwing an instance of 'itk::ImageFileReaderException'
  what():  /local/froger/miniconda/envs/_build/include/ITK-4.8/itkImageFileReader.hxx:143:
 Could not create IO object for reading file imtest_z5_y4_x3_c2.inr
...`

**Comment by dfroger** [comment]
Fixed in df824a0
