### ISSUE TITLE
tpr crashes when reading image

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#18]
image gets from https://github.com/bereziat/heimdali-test.git
`$ tpr lena.inr`
`terminate called after throwing an instance of 'itk::InvalidRequestedRegionError'
  what():  /home/local/froger/miniconda/conda-bld/work/Modules/Core/Common/src/itkDataObject.cxx:393:
Requested region is (at least partially) outside the largest possible region.
Abandon (core dumped)`

`$ inr2h5 lena.inr lena.h5`
`$ tpr lena.h5`
`terminate called after throwing an instance of 'itk::InvalidRequestedRegionError'
  what():  /home/local/froger/miniconda/conda-bld/work/Modules/Core/Common/src/itkDataObject.cxx:393:
Requested region is (at least partially) outside the largest possible region.
Abandon (core dumped)`

**Comment by dfroger** [comment]
Fixed in 3d5a9a831661dbb553edf02df209ec96794f8dbf
