### ISSUE TITLE
par does not print the number of components

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#19]
`par image.h5`
prints:
`image.h5 -z 5 -y 5 -x 5 -z0 0 -y0 0 -x0 0 -o 4`
but should be 
`image.h5        -x 5   -y 5    -z 5    -v 2    -r -o 4`

Additional issues on par output format:
1. -z and -v output are avoided if value is 1
2. -x0, -y0, -z0 are avoided if value is 0
3. a tabulation is printed between each field
4. -F= indicates the type of image. Currently, could be -F=Inrimage or
    -F=Hdf5  (but I don't know if it is possible ..)
5. coding value type (-r or -f) should be printed

**Comment by dfroger** [comment]
Fixed with 60ebd3a558a8c5ff6dca0221a029745563108ac7
