### ISSUE TITLE
Urgent and various issues on tpr

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#27]
# major issues
## tpr prints nothing

`$ tpr cossin_z5_y5_x5_c2.h5`
` `

In cmd/tpr.cxx:97:  
    NZ = zValue.getValue()==0 ? SZ-ImageIndex[2] : zValue.getValue();
    NY = yValue.getValue()==0 ? SY-ImageIndex[1] : yValue.getValue();
    NX = xValue.getValue()==0 ? SX-ImageIndex[0] : xValue.getValue();

ImageIndex[] is not initialized
## inadequate output format:

with an uncomited and ugly patch on tpr.cxx (NX, NY, NZ set to right values):
`$ tpr cossin_z5_y5_x5_c2.h5`
`[+1.0000000E+00, +0.0000000E+00]`
`[+9.8006660E-01, +0.0000000E+00]`
`...`
but should be:
`$ tpr cossin_z5_y5_x5_c2.h5`
`+1.0000000E+00 +0.0000000E+00 +9.8006660E-01 +0.0000000E+00 ...`
`...`

A working tpr is required to evaluate cco command.
# Minor issues
## Missing argument for tpr:
- -c, -cz, -l x, -f= are important missing arguments to control the output
- options to display a region of interest are also  missing (-x,-y,-z,-v,-ix,-iy,-iz,-iv)
## Ugly format of float values:

tpr prints float values with printf() , format can be controled using -f= argument

**Comment by dfroger** [comment]
Seems that -cz is bugged in Inrimage (same effect as -c)

**Comment by dfroger** [comment]
Fixed in 052872b

**Comment by bereziat** [comment]
tpr -cz is not bugged on inrimage. For instance:
$ echo 1 2 3 | cim -z 3 > t
$ tpr t
plan 1, ligne 1
1 
plan 2, ligne 1
2 
plan 3, ligne 1
3 
inrimage-extras $ tpr t -c
1 
2 
3 
inrimage-extras $ tpr t -cz
plan 1
1 
plan 2
2 
plan 3
3

**Comment by dfroger** [comment]
Here is what I get with `tpr -cz $HEIMDALI_DATA_DIR/cossin_z5_y5_x5_c2_f2.inr`:

1 0 0.980072 0 0.921065
0 0.82533 0 0.696712 0
0.980072 0 0.960525 0.0394751 0.902708
0.0773632 0.808881 0.112184 0.682826 0.142519
0.921065 0 0.902708 0.0773632 0.848356
0.151644 0.760189 0.219883 0.641703 0.279347
0.82533 0 0.808881 0.112184 0.760189
0.219883 0.681178 0.318822 0.575021 0.405051
0.696712 0 0.682826 0.142519 0.641703
0.279347 0.575021 0.405051 0.485405 0.514595
1 0 0.980072 0 0.921065
0 0.82533 0 0.696712 0
0.980072 0 0.960525 0.0394751 0.902708
0.0773632 0.808881 0.112184 0.682826 0.142519
0.921065 0 0.902708 0.0773632 0.848356
0.151644 0.760189 0.219883 0.641703 0.279347
0.82533 0 0.808881 0.112184 0.760189
0.219883 0.681178 0.318822 0.575021 0.405051
0.696712 0 0.682826 0.142519 0.641703
0.279347 0.575021 0.405051 0.485405 0.514595
1 0 0.980072 0 0.921065
0 0.82533 0 0.696712 0
0.980072 0 0.960525 0.0394751 0.902708
0.0773632 0.808881 0.112184 0.682826 0.142519
0.921065 0 0.902708 0.0773632 0.848356
0.151644 0.760189 0.219883 0.641703 0.279347
0.82533 0 0.808881 0.112184 0.760189
0.219883 0.681178 0.318822 0.575021 0.405051
0.696712 0 0.682826 0.142519 0.641703
0.279347 0.575021 0.405051 0.485405 0.514595
1 0 0.980072 0 0.921065
0 0.82533 0 0.696712 0
0.980072 0 0.960525 0.0394751 0.902708
0.0773632 0.808881 0.112184 0.682826 0.142519
0.921065 0 0.902708 0.0773632 0.848356
0.151644 0.760189 0.219883 0.641703 0.279347
0.82533 0 0.808881 0.112184 0.760189
0.219883 0.681178 0.318822 0.575021 0.405051
0.696712 0 0.682826 0.142519 0.641703
0.279347 0.575021 0.405051 0.485405 0.514595
1 0 0.980072 0 0.921065
0 0.82533 0 0.696712 0
0.980072 0 0.960525 0.0394751 0.902708
0.0773632 0.808881 0.112184 0.682826 0.142519
0.921065 0 0.902708 0.0773632 0.848356
0.151644 0.760189 0.219883 0.641703 0.279347
0.82533 0 0.808881 0.112184 0.760189
0.219883 0.681178 0.318822 0.575021 0.405051
0.696712 0 0.682826 0.142519 0.641703
0.279347 0.575021 0.405051 0.485405 0.514595
