### ISSUE TITLE
itest: compilation issue on MacOS 10.7.5

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#40]
Here the error message:

/Users/bereziat/HEIMDALI/heimdali/cmd/itest.cxx:145:53: error: no member named 'count_arguments' in
      namespace 'Heimdali'
    unsigned int numberOfInputFilenames = Heimdali::count_arguments(tclap_argv);
                                          ~~~~~~~~~~^
1 error generated.
make[3]: **\* [cmd/CMakeFiles/itest.dir/itest.cxx.o] Error 1
make[2]: **\* [cmd/CMakeFiles/itest.dir/all] Error 2
make[1]: **\* [cmd/CMakeFiles/itest.dir/rule] Error 2

**Comment by dfroger** [comment]
Can not reproduce on 10.9

**Comment by dfroger** [comment]
Which commit source files are you trying to compile?

```
git log -n 1
```

Is your working directory clean?

```
git status
```

**Comment by bereziat** [comment]
commit 6882bc3ae546fff97aa8265f556ab1d91fc9399f
Author: David Froger david.froger@inria.fr
Date:   Tue Mar 17 10:50:43 2015 +0100

```
Refactor itest
```

**Comment by dfroger** [comment]
Still don't understand why there is an error. 

`Heimdali::count_arguments` is [defined](https://github.com/dfroger/heimdali/blob/6882bc3ae546fff97aa8265f556ab1d91fc9399f/libheimdali/heimdali/cli.hxx#L23-L24) and [implemented](https://github.com/dfroger/heimdali/blob/6882bc3ae546fff97aa8265f556ab1d91fc9399f/libheimdali/cli.cxx#L46-L57).

Does a `make clean; make itest` solve the problem?

Note: I just released heimdali-0.0.7 conda packages (GNU/Linux and OS X).

**Comment by bereziat** [comment]
Yes it does:
`build/develop $ make clean`
`build/develop $ make itest`
`[ 11%] Building CXX object itkINRimageIO/CMakeFiles/itkINRImageIO.dir/src/itkINRImageIO.cxx.o`
`/Users/bereziat/HEIMDALI/heimdali/itkINRimageIO/src/itkINRImageIO.cxx:441:16: warning: explicitly`
`assigning a variable of type 'const char *' to itself [-Wself-assign]`
`InrUdetail = InrUdetail;`
`~~~~~~~~~~ ^ ~~~~~~~~~~`
`1 warning generated.`

**Comment by dfroger** [comment]
Ok, so it was an error of inconsistant rebuit.

I'll fix this warning, I think it is the last one.
