### ISSUE TITLE
muls: compilation issue on MacOS 10.7.5

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#41]
/Users/bereziat/HEIMDALI/heimdali/cmd/muls.cxx:103:1: warning: 'typename' occurs outside of a template
      [-Wc++11-extensions]
typename ThresholderType::Pointer thresholder = ThresholderType::New();
^~~~~~~~
1 warning generated.

**Comment by dfroger** [comment]
Is it just a warning, or is there also an error?

**Comment by bereziat** [comment]
Actually, It is a warning.

**Comment by dfroger** [comment]
Fixed in 9307747175aa518c78807fb6a5a9d4ee36d550f0
