### ISSUE TITLE
cim works only in interactive mode (Urgent issue)

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#43]
cim works in interactive mode (not required for heimdali). cim should read options
format (-x,-y,-v, ...) and read data from stdin, or a file (see man cim).
For instance:
`$ echo 1 2 3 4 | cim -x 2 -y 2 | tpr`
`ligne 1`
`1 2`
`ligne 2`
`3 4`

**Comment by dfroger** [comment]
Fixed in 5de66a96b4c678aa7e638fb834880abf8fc1afba
