### ISSUE TITLE
tpr: compilation issue on MacOS

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#44]
Error is:

/Users/bereziat/HEIMDALI/heimdali/cmd/tpr.cxx:97:28: error: too many arguments to function call, expected 0,
      have 1
    reader->next_iteration(io);
    ~~~~~~~~~~~~~~~~~~~~~~ ^~
/Users/bereziat/NOBACKUP/miniconda/envs/heimdali-dev/include/heimdali/cmdreader.hxx:41:9: note: 
      'next_iteration' declared here
        virtual void next_iteration() = 0;

**Comment by bereziat** [comment]
I understood my way to compile heimdali is not good (headers are taken from a wrong place). My process to compile is : 

`source activate heimdali-dev`
`CONDA_ENV_PATH=$(conda info -e | grep '*' | tr -s ' ' | cut -d" " -f3)`
`mkdir -p build`
`cd build`
`cmake -DCMAKE_PREFIX_PATH=$CONDA_ENV_PATH -DCMAKE_INSTALL_PREFIX=$CONDA_ENV_PATH ..`
`make`

what is wrong ?

**Comment by bereziat** [comment]
Finaly, I delete the folder heimaldi in:
/Users/bereziat/NOBACKUP/miniconda/envs/heimdali-dev/include
and I can now compile tpr, rdf, idf, ddf, ma, ...
I guess, something is wrong in heimdali-devel recipe conda.

**Comment by dfroger** [comment]
`heimdali-dev` is a conda environment, and has no recipe. Conda packages installed in the `heimdali-dev` environment do have recipes.

Your `heimdali-dev` environment should contains only heimdali dependencies and test utilities:
- h5unixpipe 
- itk-heimdali-dbg
-  libinrimage 
- tclap 
- cmake
-  pip 
- pexpect 

See the [doc](http://heimdali.readthedocs.org/en/develop/develop.html#install-dependencies)

I you have `heimdali` package installed in your `heimdali-dev` env, it will conflict with sources (from your Git repo) you are building. I'll add a note about this in the doc.

**Comment by bereziat** [comment]
Ok, it is clear for me now.
