### ISSUE TITLE
Minor issue: inrinfo missing.

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#46]
The command inrinfo returns:
`$ inrinfo`
`Inrimage Version 4.6.6`
`INR_HOME /usr/local/inrimage/share/inrimage`
`INR_EXTFILE /Users/bereziat/HEIMDALI/heimdali-test/inr2h5/inr_extfile`
and have also some switches (see inrinfo -help).
It could be interesting to have an inrinfo in Heimdali package to in order to test the
presence of heimdali or inrimage in test scripts.
`$ inrinfo`
`Heimdali Version 0.7.1`

inrinfo could be alias of heiminfo command.

**Comment by dfroger** [comment]
Note: compilation informations are provided by CMake
