### ISSUE TITLE
detc issue

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#47]
`$ detc lena.inr.gz -sob | tpr -c -l 10 | head -n1`
`0 22 66 22 44 110 22 22 22 44`

but should be:
`0 0.0156863 0.0470588 0.0156863 0.0313725 0.0784314 0.0156862 0.0156862 0.0156863 0.0313725`

It is due to an incorrect convertion.
detc (as arithmetics commands) should load the image and convert to
float using Inrimage conversion protocol, then, process the image.

**Comment by dfroger** [comment]
Fixed in #d7fe63d

**Comment by bereziat** [comment]
in #d7fe63d, the example below returns:
0 0.0862745 0.258824 0.0862745 0.172549 0.431373 0.0862745 0.0862745 0.0862745 0.172549
that are not the same values... and the issue should be reopened.
