### ISSUE TITLE
extg issue

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#61]
Some problems remains in closed issue #33:
- with incorrect values (out of the domain) for options -x -y -z -v -ix -iy -iz -iv, the command crashed instead of return an error message
- option -xpas without effect (extg -xpas 2 lena.inr | par -x should return -x 128, but return -x 256
- options -ypas and -zpas crashe, -vpas untested.

**Comment by dfroger** [comment]
Duplicate of #57
