### ISSUE TITLE
minor issue on tpr: indexes starts at 1 not 0

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#64]
indexes should start to 1, instead of 0.

**Comment by dfroger** [comment]
That's a conscious choice. In C++, ITK, HDF5, index start at 0.

I added a --from-zero flag to count from 0, that defaults to false.

**Comment by bereziat** [comment]
ok, but I can't see the flag (--from-zero) ...

**Comment by bereziat** [comment]
Ok, I can show the flag. Sorry :+1:
