### ISSUE TITLE
vb and vh issues

### ISSUE THREAD

**Issue by bereziat** [heimdali/heimdali#65]
usage of vb and vh is
`vb  -v <VALUE> -n <THRESHOLD> [--] [--version] [-h] <[IMAGE-IN]`
but it should be:
`vb [image-in | -] [image-out] -n seuil val`

**Comment by dfroger** [comment]
I don't think having the same flag for 2 differents things is a good idea (would be ok for example with `-n VALUE0 VALUE1 ...`).

I added the possibilty to use the two usages (`-n TRESHOLD VALUE` or `-t TRESHOLD -v VALUE`) for backward compatiblity, but I would have prefer to no maintain these design errors.

**Comment by bereziat** [comment]
We have numerous scripts that use vb/vh. So maintain -n threshold value for backward compatibility is
welcome.
